#!/bin/bash

DIR_NAME=lp

if [ $# -eq 0 ]; then
    echo "No program input supplied"
else
    ( cd $DIR_NAME
        javac *.java -nowarn
        java -cp . Lexer "../${1}"
        code=$?
        if [ $code -ne 0 ]; then
            echo "Runtime Error"
            echo "Runtime Error" > "../OUTPUT"
            exit $code
        else
            echo "SUCCESS" > "../OUTPUT"
        fi
    )
fi


