#!/bin/bash

# https://github.com/javacc/javacc/archive/javacc-7.0.11.tar.gz

DIR_NAME=lp

( cd $DIR_NAME
  javac *.java
  java -cp . Lexer "../${1}"
  if [ $? -ne 0 ]; then
        echo "Runtime Error"
        exit 1
  fi
)

echo "SUCCESS" > OUTPUT
