import java.io.File;
import java.util.Scanner;
import java.io.FileWriter;
import java.io.IOException;

import java.util.TreeMap;

// Script to reformat raw output generated by instrumented code

public class Reformat {
    public static void main(String[] args) throws IOException {
        TreeMap<String, Integer> methodCounts = new TreeMap<String, Integer>();

        Scanner scan = new Scanner(new File(args[0]));

        while (scan.hasNextLine()) {
            String methodName = scan.nextLine();
            if (!methodCounts.containsKey(methodName)) {
                methodCounts.put(methodName, 1);
            }
            else {
                methodCounts.put(methodName, methodCounts.get(methodName) + 1);
            }
        }
        scan.close();

        FileWriter output = new FileWriter(new File("output"));
        for (String methodName : methodCounts.keySet()) {
            output.write(methodName + " " + methodCounts.get(methodName) + "\n");
        }
        output.close();
    }
}
