/* Generated By:JJTree: Do not edit this line. ASTAddop.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTAddop extends SimpleNode {

  String operator;

  public ASTAddop(int id) {
    super(id);
  }

  public ASTAddop(Lexer p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(LexerVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=d05855b10bdeacabd7ab26dbeff472b9 (do not edit this line) */
