/* Generated By:JJTree: Do not edit this line. ASTActPars.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTActPars extends SimpleNode {
  public ASTActPars(int id) {
    super(id);
  }

  public ASTActPars(Lexer p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(LexerVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=4a8ee2fce7616feb2b4acb36331ec73a (do not edit this line) */
