/* Generated By:JJTree: Do not edit this line. ASTConstDecl.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTConstDecl extends SimpleNode {

  String type;

  public ASTConstDecl(int id) {
    super(id);
  }

  public ASTConstDecl(Lexer p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(LexerVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=57d3ececab5d0cc30bc7925c1e351bea (do not edit this line) */
