/* Generated By:JJTree: Do not edit this line. ASTCondFact.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTCondFact extends SimpleNode {
  public ASTCondFact(int id) {
    super(id);
  }

  public ASTCondFact(Lexer p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(LexerVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=ca54923dbbaf417fb1f2b7a41f3581e8 (do not edit this line) */
