/* Generated By:JJTree: Do not edit this line. ASTCondTerm.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTCondTerm extends SimpleNode {
  public ASTCondTerm(int id) {
    super(id);
  }

  public ASTCondTerm(Lexer p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(LexerVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=4d4e125b3eb46897cb73b29f650cbb58 (do not edit this line) */
