/* Generated By:JJTree: Do not edit this line. ASTDesignatorStmt.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTDesignatorStmt extends SimpleNode {

  boolean increment;
  boolean decrement;

  public ASTDesignatorStmt(int id) {
    super(id);
    increment = false;
    decrement = false;
  }

  public ASTDesignatorStmt(Lexer p, int id) {
    super(p, id);
    increment = false;
    decrement = false;
  }


  /** Accept the visitor. **/
  public Object jjtAccept(LexerVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=a24a70c4b2611bd644379128fcddd2dd (do not edit this line) */
