/* Generated By:JJTree: Do not edit this line. ASTDesignator.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
import java.util.ArrayList;

public class ASTDesignator extends SimpleNode {

  String name;
  ArrayList<String> modifiers;

  public ASTDesignator(int id) {
    super(id);
    modifiers = new ArrayList<String>();
  }

  public ASTDesignator(Lexer p, int id) {
    super(p, id);
    modifiers = new ArrayList<String>();
  }


  /** Accept the visitor. **/
  public Object jjtAccept(LexerVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=51109d7163d1d4235cd7653e65ba754a (do not edit this line) */
