/* Generated By:JJTree: Do not edit this line. ASTExpression.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTExpression extends SimpleNode {

  boolean leadingMinus;

  public ASTExpression(int id) {
    super(id);
    leadingMinus = false;
  }

  public ASTExpression(Lexer p, int id) {
    super(p, id);
    leadingMinus = false;
  }


  /** Accept the visitor. **/
  public Object jjtAccept(LexerVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=8512f6cf62eaface4711092e8c8a8cf4 (do not edit this line) */
