/* Generated By:JJTree: Do not edit this line. ASTEnumDecl.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTEnumDecl extends SimpleNode {

  String name;

  public ASTEnumDecl(int id) {
    super(id);
  }

  public ASTEnumDecl(Lexer p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(LexerVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=9c60e6cfffeb59100c12c124dba2ad32 (do not edit this line) */
