/* Generated By:JJTree: Do not edit this line. ASTFormPars.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTFormPars extends SimpleNode {
  public ASTFormPars(int id) {
    super(id);
  }

  public ASTFormPars(Lexer p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(LexerVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=5d94eedc47b4887d940cc0340bd67ffd (do not edit this line) */
