/* Generated By:JJTree: Do not edit this line. ASTFactor.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */

enum FactorType {
  DESIGNATOR,
  ACTPARS,
  NUMCONST,
  CHARCONST,
  BOOLCONST,
  NEW,
  EXPRESSION
}

public class ASTFactor extends SimpleNode {

  FactorType type;
  int numConst;
  String charConst;
  boolean boolConst;

  public ASTFactor(int id) {
    super(id);
  }

  public ASTFactor(Lexer p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(LexerVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=66a1dea0d2b47062000c1b55500d79c3 (do not edit this line) */
