/* Generated By:JJTree: Do not edit this line. ASTInterfaceMethodDecl.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTInterfaceMethodDecl extends SimpleNode {

  String name;
  String returnType;

  public ASTInterfaceMethodDecl(int id) {
    super(id);
  }

  public ASTInterfaceMethodDecl(Lexer p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(LexerVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=9a8e74a0ad7e0959d9ca18cf033152b1 (do not edit this line) */
