/* Generated By:JJTree: Do not edit this line. ASTInterfaceDecl.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTInterfaceDecl extends SimpleNode {

  String name;

  public ASTInterfaceDecl(int id) {
    super(id);
  }

  public ASTInterfaceDecl(Lexer p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(LexerVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=3ffb7b7703cffb752b904140ebc66b9c (do not edit this line) */
