/* Generated By:JJTree: Do not edit this line. ASTMethodDecl.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTMethodDecl extends SimpleNode {

  String name;
  String returnType;

  public ASTMethodDecl(int id) {
    super(id);
  }

  public ASTMethodDecl(Lexer p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(LexerVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=2128dd05b328a7b3ffce06d3aa874ce0 (do not edit this line) */
