/* Generated By:JJTree: Do not edit this line. ASTProgram.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTProgram extends SimpleNode {

  String name;

  public ASTProgram(int id) {
    super(id);
  }

  public ASTProgram(Lexer p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(LexerVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=1efa20843742054954bf00ec7375b592 (do not edit this line) */
