/* Generated By:JJTree: Do not edit this line. ASTParameter.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTParameter extends SimpleNode {

  String name;
  String type;
  boolean isArray;

  public ASTParameter(int id) {
    super(id);
  }

  public ASTParameter(Lexer p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(LexerVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=c3ab256cd73c9125efead658635dd9d8 (do not edit this line) */
