/* Generated By:JJTree: Do not edit this line. ASTRelop.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTRelop extends SimpleNode {

  String relation;

  public ASTRelop(int id) {
    super(id);
  }

  public ASTRelop(Lexer p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(LexerVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=fe4ebb9f93f5ca32b4eaefd6250f9bf0 (do not edit this line) */
