/* Generated By:JJTree: Do not edit this line. ASTStmt.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */

import java.util.ArrayList;

enum StmtType {
  DESIGNATOR,
  IF,
  IF_ELSE,
  FOR,
  BREAK,
  CONTINUE,
  RETURN,
  READ,
  PRINTF,
  BLOCK
}

public class ASTStmt extends SimpleNode {

  StmtType type;
  int forMask;
  ArrayList<Integer> printNums;

  public ASTStmt(int id) {
    super(id);
    forMask = 0;
    printNums = new ArrayList<Integer>();
  }

  public ASTStmt(Lexer p, int id) {
    super(p, id);
    forMask = 0;
    printNums = new ArrayList<Integer>();
  }


  /** Accept the visitor. **/
  public Object jjtAccept(LexerVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=a94f156528ea72a67fdc873b69b92b45 (do not edit this line) */
