/* Generated By:JJTree: Do not edit this line. ASTVarDecl.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTVarDecl extends SimpleNode {

  String type;

  public ASTVarDecl(int id) {
    super(id);
  }

  public ASTVarDecl(Lexer p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(LexerVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=a5ab9abe442a9104baea041762317b6e (do not edit this line) */
