/* Generated By:JavaCC: Do not edit this line. LexerVisitor.java Version 4.1d1 */
public interface LexerVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTStart node, Object data);
  public Object visit(ASTProgram node, Object data);
  public Object visit(ASTConstDecl node, Object data);
  public Object visit(ASTConst node, Object data);
  public Object visit(ASTEnumDecl node, Object data);
  public Object visit(ASTEnum node, Object data);
  public Object visit(ASTVarDecl node, Object data);
  public Object visit(ASTVar node, Object data);
  public Object visit(ASTStructDecl node, Object data);
  public Object visit(ASTInterfaceDecl node, Object data);
  public Object visit(ASTInterfaceMethodDecl node, Object data);
  public Object visit(ASTMethodDecl node, Object data);
  public Object visit(ASTFormPars node, Object data);
  public Object visit(ASTParameter node, Object data);
  public Object visit(ASTStmt node, Object data);
  public Object visit(ASTDesignatorStmt node, Object data);
  public Object visit(ASTActPars node, Object data);
  public Object visit(ASTCondition node, Object data);
  public Object visit(ASTCondTerm node, Object data);
  public Object visit(ASTCondFact node, Object data);
  public Object visit(ASTExpression node, Object data);
  public Object visit(ASTTerm node, Object data);
  public Object visit(ASTFactor node, Object data);
  public Object visit(ASTDesignator node, Object data);
  public Object visit(ASTAssignop node, Object data);
  public Object visit(ASTRelop node, Object data);
  public Object visit(ASTAddop node, Object data);
  public Object visit(ASTMulop node, Object data);
}
/* JavaCC - OriginalChecksum=fa95fe3f01a6d1ccf922765d372a3b5e (do not edit this line) */
