/* Generated By:JavaCC: Do not edit this line. LexerTreeConstants.java Version 4.1d1 */
public interface LexerTreeConstants
{
  public int JJTSTART = 0;
  public int JJTPROGRAM = 1;
  public int JJTCONSTDECL = 2;
  public int JJTCONST = 3;
  public int JJTVOID = 4;
  public int JJTENUMDECL = 5;
  public int JJTENUM = 6;
  public int JJTVARDECL = 7;
  public int JJTVAR = 8;
  public int JJTSTRUCTDECL = 9;
  public int JJTINTERFACEDECL = 10;
  public int JJTINTERFACEMETHODDECL = 11;
  public int JJTMETHODDECL = 12;
  public int JJTFORMPARS = 13;
  public int JJTPARAMETER = 14;
  public int JJTSTMT = 15;
  public int JJTDESIGNATORSTMT = 16;
  public int JJTACTPARS = 17;
  public int JJTCONDITION = 18;
  public int JJTCONDTERM = 19;
  public int JJTCONDFACT = 20;
  public int JJTEXPRESSION = 21;
  public int JJTTERM = 22;
  public int JJTFACTOR = 23;
  public int JJTDESIGNATOR = 24;
  public int JJTASSIGNOP = 25;
  public int JJTRELOP = 26;
  public int JJTADDOP = 27;
  public int JJTMULOP = 28;


  public String[] jjtNodeName = {
    "Start",
    "Program",
    "ConstDecl",
    "Const",
    "void",
    "EnumDecl",
    "Enum",
    "VarDecl",
    "Var",
    "StructDecl",
    "InterfaceDecl",
    "InterfaceMethodDecl",
    "MethodDecl",
    "FormPars",
    "Parameter",
    "Stmt",
    "DesignatorStmt",
    "ActPars",
    "Condition",
    "CondTerm",
    "CondFact",
    "Expression",
    "Term",
    "Factor",
    "Designator",
    "Assignop",
    "Relop",
    "Addop",
    "Mulop",
  };
}
/* JavaCC - OriginalChecksum=f5d342b94862f76245c87e28b526c67d (do not edit this line) */
